### ISSUE TITLE
pypy 2.7-v7.3.15 failed to build against latest xcode

### ISSUE THREAD

**Issue by chenrui333** [pypy/pypy#4931]
👋 there is some issue of regression build pypy 2.7-v7.3.15 against latest xcode as below:

```
/private/tmp/pypy-20240330-5072-4eagj6/pypy2.7-v7.3.15-src/lib_pypy/cffi/cparser.py:165: UserWarning: Global variable 'gdbm_errno' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
_gdbm_cffi.c:965:36: error: incompatible function pointer types passing 'void (*)(void)' to parameter of type 'void (*)(const char *)' [-Wincompatible-function-pointer-types]
  return gdbm_open(x0, x1, x2, x3, x4);
                                   ^~
/usr/local/include/gdbm.h:127:15: note: passing argument to parameter here
                            void (*)(const char *));
                                   ^
_gdbm_cffi.c:1132:10: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  return gdbm_strerror(x0);
         ^~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

relates to https://github.com/Homebrew/homebrew-core/pull/167577

**Comment by mattip** [comment]
If I understand correctly the error comes from the `lib.NULL` argument here https://github.com/pypy/pypy/blob/fa71656049ddec0a11c63b292a934c3837fac35f/lib_pypy/gdbm.py#L31. The corresponding code in [CPython is](https://github.com/python/cpython/blob/9dae05ee59eeba0e67af2a46f2a2907c9f8d7e4a/Modules/_gdbmmodule.c#L89)
```
gdbm_open((char *)file, 0, flags, mode, NULL);
```

Does CPython work unpatched?

**Comment by chenrui333** [comment]
yeah, cython works unpatched, you can see in here, https://github.com/Homebrew/homebrew-core/blob/master/Formula/c/cython.rb

**Comment by chenrui333** [comment]
actually I could not find that ref in the v3 source tree?

**Comment by mattip** [comment]
Not Cython: CPython. What version of xcode is problematic?

**Comment by carlocab** [comment]
CPython seems to build fine. The problematic versions of Xcode appear to Xcode 15+.

**Comment by mattip** [comment]
I cannot reproduce this with xcode 15.0.0. What exactly are you running? Is this with x86_64 or arm64?

**Comment by carlocab** [comment]
Sorry, my mistake. The problem appears with Xcode 15.3 on both x86_64 or arm64. It does not appear on Xcode 15.2.

**Comment by mattip** [comment]
For me that is a warning, not an error. Do you have a global environment variable with `-Werror` set? Fixed in ec7391c43f to remove the warning, thanks.

Closing

**Comment by carlocab** [comment]
No. Not sure why it is different for you:
```c
// test.c
void (*test)(void);
void foo(void (*in)(const char *)) {}

int main(void) {
    foo(test);
    return 0;
}
```
```
❯ /usr/bin/clang --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
❯ /usr/bin/clang test.c
test.c:5:9: error: incompatible function pointer types passing 'void (*)(void)' to parameter of type 'void (*)(const char *)' [-Wincompatible-function-pointer-types]
    foo(test);
        ^~~~
test.c:2:17: note: passing argument to parameter 'in' here
void foo(void (*in)(const char *)) {}
                ^
1 error generated.
```

**Comment by mattip** [comment]
That test.c failure reproduces, but I can build `gdbm` on main with the gdbm supplied by homebrew
```
cd lib_pypy
CFLAGS="-I /opt/homebrew/include -Werror" LDFLAGS="-L/opt/homebrew/lib"  ../pypy/goal/pypy-c pypy_tools/build_cffi_imports.py --rebuild --only gdbm
```

as well as the embedded one used by the buildbot
```
cd lib_pypy
../pypy/goal/pypy3.9-c pypy_tools/build_cffi_imports.py --embed-dependencies --rebuild --only gdbm
```

**Comment by mattip** [comment]
Is it still failing for you on HEAD? I will reopen

**Comment by carlocab** [comment]
Still failing on HEAD, but somewhere else this time:
```
_curses_cffi.c:6876:32: error: incompatible function pointer types assigning to 'char *(*)(char *, ...)' from 'char *(const char *, ...)' [-Wincompatible-function-pointer-types]
  *(char *(* *)(char *, ...))o = tparm;
                               ^ ~~~~~
```
Happy to provide build logs if needed.

**Comment by mattip** [comment]
On my macos, `man tparm` gives this signature:
```
char *tparm(char *str, ...);
```
I wonder where the `const char` delcaration comes from on your system
